# Taken from the lab 4 on Flask and modified accordingly.
# To build the image : docker build -t minetexture -f docker/Dockerfile.flask .
# To run the container : docker run -p 9090:8080 minetexture
FROM python:3.11-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY pyproject.toml uv.lock .
RUN uv sync --frozen --no-dev --no-install-project

COPY src/minetexture/flask .

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8080

CMD ["flask", "--app", "core", "run", "--host=0.0.0.0", "--port=8080"]
